import type { Metadata } from "next";
import LegalLayout, { type LegalSection } from "../components/LegalLayout";

export const metadata: Metadata = { title: "Politique de confidentialité" };
const mail = <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>;
const sections: LegalSection[] = [
  {id:"responsable",number:"01",title:"Responsable du traitement",content:<div className="contact-box"><p><strong>GOMES PINTO BARRETO Lenny</strong><br/>Auto-entrepreneur — SIRET : 93883298700011<br/>Contact : {mail}</p></div>},
  {id:"collecte",number:"02",title:"Données collectées",content:<><h3>2.1 · Données fournies par l’utilisateur</h3><ul><li>adresse email et nom d’utilisateur ;</li><li>mot de passe stocké sous forme sécurisée, jamais en clair ;</li><li>photo de profil et vidéo vitrine verticale de 30 secondes maximum ;</li><li>ville, bio et styles de danse.</li></ul><h3>2.2 · Données collectées automatiquement</h3><ul><li>position géographique, uniquement avec autorisation explicite ;</li><li>token de notification push ;</li><li>date et heure de connexion et statut en ligne.</li></ul><h3>2.3 · Connexion via Google</h3><p>En cas de connexion avec Google, ViewZ collecte uniquement l’adresse email, le nom d’affichage et, si disponible, la photo de profil Google.</p></>},
  {id:"finalites",number:"03",title:"Finalités du traitement",content:<table className="data-table"><thead><tr><th>Finalité</th><th>Base légale</th></tr></thead><tbody><tr><td>Création et gestion du compte</td><td>Exécution du contrat</td></tr><tr><td>Danseurs et annonces à proximité</td><td>Consentement</td></tr><tr><td>Notifications push</td><td>Consentement</td></tr><tr><td>« Je danse maintenant »</td><td>Consentement</td></tr><tr><td>Amélioration de l’application</td><td>Intérêt légitime</td></tr><tr><td>Obligations légales</td><td>Obligation légale</td></tr></tbody></table>},
  {id:"geolocalisation",number:"04",title:"Données de localisation",content:<><p>ViewZ utilise la géolocalisation pour :</p><ul><li>afficher les annonces et danseurs proches de toi ;</li><li>permettre la fonctionnalité « Je danse maintenant » ;</li><li>mettre à jour ta position dans l’application.</li></ul><p>La géolocalisation est strictement optionnelle. Ta position exacte n’est jamais affichée publiquement.</p></>},
  {id:"hebergement",number:"05",title:"Hébergement et sous-traitants",content:<table className="data-table"><thead><tr><th>Service</th><th>Rôle</th><th>Localisation</th></tr></thead><tbody><tr><td>Railway</td><td>Backend</td><td>États-Unis</td></tr><tr><td>Neon</td><td>Base PostgreSQL</td><td>États-Unis</td></tr><tr><td>Cloudflare R2</td><td>Photos et vidéos</td><td>UE / États-Unis</td></tr><tr><td>Expo</td><td>Notifications</td><td>États-Unis</td></tr><tr><td>Google</td><td>OAuth optionnel</td><td>États-Unis</td></tr><tr><td>Resend</td><td>Envoi des demandes de suppression</td><td>États-Unis</td></tr></tbody></table>},
  {id:"conservation",number:"06",title:"Durée de conservation",content:<table className="data-table"><thead><tr><th>Donnée</th><th>Durée</th></tr></thead><tbody><tr><td>Données de compte</td><td>Jusqu’à suppression du compte</td></tr><tr><td>Messages</td><td>Jusqu’à suppression du compte</td></tr><tr><td>« Je danse maintenant »</td><td>Durée choisie par l’utilisateur</td></tr><tr><td>Logs de connexion</td><td>12 mois</td></tr><tr><td>Données après suppression</td><td>30 jours puis suppression définitive</td></tr></tbody></table>},
  {id:"droits",number:"07",title:"Tes droits (RGPD)",content:<><ul><li><strong>Droit d’accès :</strong> obtenir une copie de tes données ;</li><li><strong>Droit de rectification :</strong> corriger les données inexactes ;</li><li><strong>Droit à l’effacement :</strong> demander leur suppression ;</li><li><strong>Droit à la portabilité :</strong> les recevoir dans un format structuré ;</li><li><strong>Droit d’opposition :</strong> t’opposer à certains traitements ;</li><li><strong>Retrait du consentement :</strong> à tout moment.</li></ul><p>Pour exercer ces droits : {mail}. En cas de réclamation non résolue, tu peux contacter la <a href="https://www.cnil.fr" target="_blank" rel="noreferrer">CNIL</a>.</p></>},
  {id:"securite",number:"08",title:"Sécurité",content:<ul><li>mots de passe protégés avec bcrypt ;</li><li>communications chiffrées avec HTTPS/TLS ;</li><li>authentification par token JWT ;</li><li>accès à la base de données restreint.</li></ul>},
  {id:"cookies",number:"09",title:"Cookies et traceurs",content:<p>ViewZ est une application mobile et n’utilise pas de cookies. Un token JWT est stocké localement pour maintenir la session ; il est strictement nécessaire au fonctionnement.</p>},
  {id:"mineurs",number:"10",title:"Mineurs",content:<p>ViewZ est accessible aux personnes de 13 ans et plus. Les utilisateurs de moins de 16 ans doivent avoir obtenu le consentement de leur représentant légal.</p>},
  {id:"modifications",number:"11",title:"Modifications",content:<><p>En cas de modification substantielle de cette politique, tu seras notifié via l’application.</p><div className="contact-box"><p>Contact : {mail}</p></div></>},
];
export default function PrivacyPage(){return <LegalLayout title="Politique de confidentialité" kicker="DONNÉES & VIE PRIVÉE" sections={sections}/>}
