import type { Metadata } from "next";
import LegalLayout, { type LegalSection } from "../components/LegalLayout";

export const metadata: Metadata = { title: "Conditions générales d’utilisation" };
const mail = <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>;
const sections: LegalSection[] = [
  {id:"editeur",number:"01",title:"Éditeur de l’application",content:<div className="contact-box"><p><strong>GOMES PINTO BARRETO Lenny</strong><br/>Auto-entrepreneur<br/>SIRET : 93883298700011<br/>Contact : {mail}</p></div>},
  {id:"objet",number:"02",title:"Objet",content:<><p>ViewZ est une application mobile communautaire dédiée aux danseurs. Elle permet aux utilisateurs de publier des annonces, trouver des partenaires de danse, partager leur localisation en temps réel, accéder à une carte des spots de danse et communiquer via un système de messagerie intégré.</p><p>Les présentes Conditions Générales d’Utilisation (CGU) définissent les modalités d’accès et d’utilisation de l’application ViewZ.</p></>},
  {id:"acceptation",number:"03",title:"Acceptation des CGU",content:<p>L’utilisation de ViewZ implique l’acceptation pleine et entière des présentes CGU. En créant un compte ou en utilisant l’application, l’utilisateur reconnaît avoir lu, compris et accepté ces conditions.</p>},
  {id:"acces",number:"04",title:"Accès à l’application",content:<><p>L’application est accessible gratuitement à toute personne disposant d’un accès internet et d’un appareil compatible iOS ou Android. L’éditeur se réserve le droit de suspendre, modifier ou interrompre l’accès à tout ou partie de l’application, sans préavis ni indemnité.</p><p>ViewZ est réservée aux personnes âgées de 13 ans ou plus. En dessous de 16 ans, l’accord d’un représentant légal est requis conformément au RGPD.</p></>},
  {id:"compte",number:"05",title:"Création de compte",content:<><p>Pour accéder aux fonctionnalités, l’utilisateur doit créer un compte en fournissant :</p><ul><li>une adresse email valide ;</li><li>un nom d’utilisateur unique ;</li><li>un mot de passe sécurisé.</li></ul><p>L’utilisateur est seul responsable de la confidentialité de ses identifiants et de toute activité réalisée depuis son compte. L’éditeur peut suspendre ou supprimer tout compte en cas de non-respect des présentes CGU.</p></>},
  {id:"contenus",number:"06",title:"Contenu publié par les utilisateurs",content:<><h3>6.1 · Responsabilité de l’utilisateur</h3><p>L’utilisateur est seul responsable des contenus qu’il publie sur ViewZ (annonces, photos, vidéos, messages). Il garantit disposer de tous les droits nécessaires et que ces contenus ne violent aucun droit de tiers.</p><h3>6.2 · Contenus interdits</h3><p>Il est strictement interdit de publier des contenus :</p><ul><li>contraires aux lois et règlements en vigueur ;</li><li>haineux, discriminatoires, diffamatoires ou obscènes ;</li><li>portant atteinte à la vie privée d’autrui ;</li><li>contenant des données personnelles de tiers sans consentement ;</li><li>violant des droits de propriété intellectuelle ;</li><li>à caractère commercial ou publicitaire non autorisé.</li></ul><h3>6.3 · Vidéos et musique</h3><p>La publication de vidéos contenant des œuvres musicales protégées sans autorisation peut engager la responsabilité personnelle de l’utilisateur. ViewZ n’est pas responsable des contenus publiés par ses utilisateurs au sens de la LCEN.</p><h3>6.4 · Signalement</h3><p>Tout utilisateur peut signaler un contenu inapproprié via l’application ou par email à {mail}. L’éditeur s’engage à traiter les signalements dans les meilleurs délais et à retirer les contenus manifestement illicites.</p></>},
  {id:"localisation",number:"07",title:"Données de localisation",content:<><p>ViewZ utilise la géolocalisation de l’appareil pour afficher les danseurs et annonces à proximité. Cette fonctionnalité nécessite l’autorisation explicite de l’utilisateur. Les données de localisation ne sont pas vendues à des tiers.</p><p>« Je danse maintenant » permet de partager sa position avec les autres utilisateurs pendant une durée limitée choisie par l’utilisateur. Cette fonctionnalité est volontaire et peut être désactivée à tout moment.</p></>},
  {id:"propriete",number:"08",title:"Propriété intellectuelle",content:<p>La marque ViewZ, le logo, le design de l’application et tous les contenus produits par l’éditeur sont la propriété exclusive de GOMES PINTO BARRETO Lenny et sont protégés par le droit de la propriété intellectuelle. Toute reproduction, représentation ou exploitation non autorisée est interdite.</p>},
  {id:"responsabilite",number:"09",title:"Disponibilité et responsabilité",content:<><p>L’éditeur s’efforce d’assurer la disponibilité de l’application, sans pouvoir garantir un accès ininterrompu. ViewZ est fournie « en l’état » sans garantie d’aucune sorte.</p><p>L’éditeur ne saurait être tenu responsable :</p><ul><li>des dommages directs ou indirects liés à l’utilisation de l’application ;</li><li>des contenus publiés par les utilisateurs ;</li><li>des interactions entre utilisateurs hors de l’application ;</li><li>des interruptions liées à des tiers.</li></ul></>},
  {id:"resiliation",number:"10",title:"Suspension et résiliation",content:<><p>L’éditeur peut suspendre ou supprimer sans préavis un compte en cas de non-respect des CGU, de comportement frauduleux ou abusif, ou de signalements répétés et avérés.</p><p>L’utilisateur peut supprimer son compte à tout moment depuis les paramètres de l’application.</p></>},
  {id:"modification",number:"11",title:"Modification des CGU",content:<p>L’éditeur peut modifier les présentes CGU à tout moment. Toute modification significative sera notifiée dans l’application. La poursuite de son utilisation après modification vaut acceptation des nouvelles CGU.</p>},
  {id:"droit",number:"12",title:"Droit applicable et juridiction",content:<><p>Les présentes CGU sont soumises au droit français. En cas de litige, une solution amiable sera recherchée en priorité. À défaut, les tribunaux français seront seuls compétents.</p><div className="contact-box"><p>Pour toute question : {mail}</p></div></>},
];
export default function CguPage(){return <LegalLayout title="Conditions générales d’utilisation" kicker="CADRE D’UTILISATION" sections={sections}/>}
